apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: Selector Label
  type: NodePort
  ports:
    - name: posts
      protocol: TCP
      port: 80
      targetPort: 8080
