# apiVersion: v1
# kind: Service
# metadata:
#   name: post-service
# spec:
#   selector:
#     app: posts
#   type: ClusterIP
#   ports:
#     - name: posts
#       protocol: TCP
#       port: 4000
#       targetPort: 4000

