apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: posts
  type: NodePort
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000
