apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: "yasniel1408/event-bus:latest"
          resources:
            limits:
              cpu: 800m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 250Mi
